# Generated by Django 4.1.5 on 2023-03-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.CharField(max_length=15, verbose_name="Number")),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="header/logo", verbose_name="Logo"),
                ),
                (
                    "favicon",
                    models.ImageField(
                        upload_to="header/favicon", verbose_name="Favicon"
                    ),
                ),
                (
                    "appointment",
                    models.CharField(
                        default="Your Answer",
                        max_length=150,
                        verbose_name="Appointment Text",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="Crousel", verbose_name="Crousel Image"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Short Title"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StotraAndStutiCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, unique=True, verbose_name="Title"),
                ),
                (
                    "desc",
                    models.TextField(max_length=200, verbose_name="Short Description"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Video Title")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="video/thumbnail", verbose_name="Thumbnail"
                    ),
                ),
                (
                    "vid",
                    models.FileField(
                        blank=True, null=True, upload_to="video", verbose_name="File"
                    ),
                ),
                (
                    "path",
                    models.URLField(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Youtube Embed Video Url",
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Video Description",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StotraAndStuti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(upload_to="stotra", verbose_name="Upload Image"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.stotraandstuticategory",
                        verbose_name="category",
                    ),
                ),
            ],
        ),
    ]
