# Generated by Django 4.1.5 on 2023-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=15, verbose_name='Number')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='appointment',
            field=models.CharField(default='Your Answer', max_length=150, verbose_name='Appointment Text'),
        ),
    ]
