# Generated by Django 4.1.5 on 2023-03-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                ("message", models.TextField(verbose_name="Comment")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="header",
            name="appointment",
            field=models.CharField(
                default="Your Answer", max_length=250, verbose_name="Appointment Text"
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="img",
            field=models.ImageField(upload_to="Banner", verbose_name="Banner Image"),
        ),
    ]
