# Generated by Django 4.1.5 on 2023-03-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comment_alter_email_email_alter_header_appointment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date & Time"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Phone Number")),
                ("token", models.CharField(max_length=50, verbose_name="Token")),
                (
                    "date_time",
                    models.DateTimeField(verbose_name="Appointment Date & Time"),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
