# Generated by Django 4.1.5 on 2023-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="StotraAndStutiCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, unique=True, verbose_name="Title"),
                ),
                (
                    "desc",
                    models.TextField(max_length=200, verbose_name="Short Description"),
                ),
            ],
        ),
    ]
