# Generated by Django 4.1.5 on 2023-03-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "src",
                    models.URLField(
                        help_text="Embeded Iframe src link", verbose_name="Embeded URL"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(max_length=50, verbose_name="Facebook Account"),
                ),
                (
                    "twitter",
                    models.CharField(max_length=50, verbose_name="Twitter Account"),
                ),
                (
                    "instagram",
                    models.CharField(max_length=50, verbose_name="Instagram Account"),
                ),
                (
                    "youtube",
                    models.CharField(max_length=50, verbose_name="Youtube Account"),
                ),
                (
                    "linkedin",
                    models.CharField(max_length=50, verbose_name="Linkedin Account"),
                ),
            ],
        ),
    ]
