# Generated by Django 4.1.5 on 2023-03-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_address_sociallinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.TextField(verbose_name="About")),
                ("img", models.ImageField(upload_to=None, verbose_name="Image")),
            ],
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Facebook Account"
            ),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Instagram Account"
            ),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="linkedin",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Linkedin Account"
            ),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Twitter Account"
            ),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="youtube",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Youtube Account"
            ),
        ),
    ]
