# Generated by Django 4.1.5 on 2023-02-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_stotraandstuti"),
    ]

    operations = [
        migrations.AddField(
            model_name="stotraandstuti",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.stotraandstuticategory",
                verbose_name="category",
            ),
            preserve_default=False,
        ),
    ]
