# Generated by Django 4.1.5 on 2023-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_aboutus_alter_sociallinks_facebook_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="videoid",
            field=models.CharField(
                default="None", max_length=50, verbose_name="Video ID"
            ),
        ),
    ]
