# Generated by Django 4.1.5 on 2023-02-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_stotraandstuti_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Video Title")),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="video/thumbnail", verbose_name="Thumbnail"
                    ),
                ),
                ("vid", models.FileField(upload_to="video", verbose_name="File")),
                ("path", models.URLField(verbose_name="Youtube Embed Video Url")),
                (
                    "desc",
                    models.CharField(max_length=50, verbose_name="Video Description"),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.category",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
