# Generated by Django 4.1.5 on 2023-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_category_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="desc",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Video Description"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="path",
            field=models.URLField(
                blank=True,
                default="",
                null=True,
                verbose_name="Youtube Embed Video Url",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="vid",
            field=models.FileField(
                blank=True, null=True, upload_to="video", verbose_name="File"
            ),
        ),
    ]
